spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1pbjmlk6672o86bro.mysql.rds.aliyuncs.com:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: njnufxd
    password: Njnufxd1105
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb


mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml

